In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_excel("/content/EPA data.xlsx")
df

,1. FORM TYPE,2. REPORTING YEAR,3. TRIFD,4. FACILITY NAME,5. FACILITY STREET,6. FACILITY CITY,7. FACILITY COUNTY,8. FACILITY STATE,9. FACILITY ZIP CODE,10. BIA CODE,...,78. PFAS IND,79. METAL IND,80. REVISION CODE 1,81. REVISION CODE 2,82. COMMENT SEQUENCE,83. SECTION,84. COMMENT TYPE,85. COMMENT TYPE DESCRIPTION,86. COMMENT TEXT,20221110
0,R,2017,68301NRGYD13238,E ENERGY ADAMS,13238 E ASPEN RD,ADAMS,GAGE,NE,68301,NaN,...,NO,NO,RR1,RR2,444032,9.1,REV,Reason for Revision,Upon review of the Fermentation Scrubber Conti...,NaN
1,R,2017,38326TNNSSHIGHW,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,HARDIN,TN,38326,NaN,...,NO,NO,NaN,NaN,336654,9.1,PE119,You have reported 0 lbs transferred off-site.,Error Reviewed / No Comment.,NaN
2,R,2017,38326TNNSSHIGHW,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,HARDIN,TN,38326,NaN,...,NO,NO,NaN,NaN,336653,9.1,PE54,"You checked the ""Not Applicable"" box for the o...",Error Reviewed / No Comment.,NaN
3,R,2017,38326TNNSSHIGHW,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,HARDIN,TN,38326,NaN,...,NO,NO,NaN,NaN,336652,9.1,9.1,Other Miscellaneous Information:,Off-site transfers are made to the PCA off-sit...,NaN
4,R,2017,53121SNPND1001E,APPLIED MATERIAL SOLUTIONS INC,1001 E CENTRALIA ST,ELKHORN,WALWORTH,WI,53121,NaN,...,NO,NO,NaN,NaN,324391,9.1,DB NUM,Dun and Bradstreet Not Applicable,Have not applied for one.,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41011,R,2017,28120MRCNF22AME,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,GASTON,NC,28120,NaN,...,NO,NO,NaN,NaN,298810,9.1,PE110,Chemical specific warning,Error Reviewed / No Comment.,NaN
41012,R,2017,28120MRCNF22AME,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,GASTON,NC,28120,NaN,...,NO,NO,NaN,NaN,298809,9.1,DQA98,Change in the total quantity of production-rel...,This change in release totals was expected.,NaN
41013,R,2017,28120MRCNF22AME,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,GASTON,NC,28120,NaN,...,NO,NO,NaN,NaN,298808,9.1,DQA97,Change in the total release quantity,This change in release totals was expected.,NaN
41014,R,2017,1304WCVLLY3156F,C'VILLE YOGHURT INC,3156 FINGER LAKES E DR,CORTLAND,CORTLAND,NY,13045,NaN,...,NO,NO,NaN,NaN,295275,9.1,PRAI,Production or Activity Variable,Nitric acid is a component in a chemical used ...,NaN
41015,R,2017,7494WKFDSN1NWIL,OK FOODS INC-MULDROW,100 N WILSON ROCK RD,MULDROW,SEQUOYAH,OK,74948,NaN,...,NO,NO,NaN,NaN,292344,9.1,PROD,Changes in Production Levels,Increased water throughput correlates to the i...,NaN

In [ ]:
df2=df.iloc[:,[3,4,5,40,41,64]]

In [ ]:
df2

,4. FACILITY NAME,5. FACILITY STREET,6. FACILITY CITY,41. LATITUDE,42. LONGITUDE,65. PARENT COMPANY NAME
0,E ENERGY ADAMS,13238 E ASPEN RD,ADAMS,40.484200,-96.545900,NaN
1,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,35.049000,-88.267000,PACKAGING CORP OF AMERICA
2,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,35.049000,-88.267000,PACKAGING CORP OF AMERICA
3,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,35.049000,-88.267000,PACKAGING CORP OF AMERICA
4,APPLIED MATERIAL SOLUTIONS INC,1001 E CENTRALIA ST,ELKHORN,42.663870,-88.525900,APPLIED MATERIAL SOLUTIONS INC
...,...,...,...,...,...,...
41011,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,35.290620,-81.011810,AMERICAN & EFIRD LLC
41012,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,35.290620,-81.011810,AMERICAN & EFIRD LLC
41013,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,35.290620,-81.011810,AMERICAN & EFIRD LLC
41014,C'VILLE YOGHURT INC,3156 FINGER LAKES E DR,CORTLAND,42.561333,-76.229650,NaN
41015,OK FOODS INC-MULDROW,100 N WILSON ROCK RD,MULDROW,35.409028,-94.582417,OK FOODS INC

In [ ]:
df2.columns=["NAME","STREET","CITY","LAT","LONG","PARENT"]
df2

,NAME,STREET,CITY,LAT,LONG,PARENT
0,E ENERGY ADAMS,13238 E ASPEN RD,ADAMS,40.484200,-96.545900,NaN
1,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,35.049000,-88.267000,PACKAGING CORP OF AMERICA
2,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,35.049000,-88.267000,PACKAGING CORP OF AMERICA
3,PACKAGING CORP OF AMERICA COUNCE MILL,HWY 57,COUNCE,35.049000,-88.267000,PACKAGING CORP OF AMERICA
4,APPLIED MATERIAL SOLUTIONS INC,1001 E CENTRALIA ST,ELKHORN,42.663870,-88.525900,APPLIED MATERIAL SOLUTIONS INC
...,...,...,...,...,...,...
41011,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,35.290620,-81.011810,AMERICAN & EFIRD LLC
41012,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,35.290620,-81.011810,AMERICAN & EFIRD LLC
41013,AMERICAN & EFIRD LLC PLANT 05 & 15,601 AMERICAN ST,MOUNT HOLLY,35.290620,-81.011810,AMERICAN & EFIRD LLC
41014,C'VILLE YOGHURT INC,3156 FINGER LAKES E DR,CORTLAND,42.561333,-76.229650,NaN
41015,OK FOODS INC-MULDROW,100 N WILSON ROCK RD,MULDROW,35.409028,-94.582417,OK FOODS INC

In [ ]:
df2.sort_values("NAME")

,NAME,STREET,CITY,LAT,LONG,PARENT
6041,1I BRANCH - SPECIALTY SERVICES COMPLEX,233 HOYT ROAD,WAXAHACHIE,32.363739,-96.940481,UNIVAR SOLUTIONS USA INC
7916,1I BRANCH - SPECIALTY SERVICES COMPLEX,233 HOYT ROAD,WAXAHACHIE,32.363739,-96.940481,UNIVAR SOLUTIONS USA INC
28495,1I BRANCH - SPECIALTY SERVICES COMPLEX,233 HOYT ROAD,WAXAHACHIE,32.363739,-96.940481,UNIVAR SOLUTIONS USA INC
3892,1I BRANCH - SPECIALTY SERVICES COMPLEX,233 HOYT ROAD,WAXAHACHIE,32.363739,-96.940481,UNIVAR SOLUTIONS USA INC
11205,3 SIGMA LLC,1985 W STANFIELD RD,TROY,40.050330,-84.241830,DURACO SPECIALTY TAPES LLC
...,...,...,...,...,...,...
15486,ZIPPO MANUFACTURING CO,401 CONGRESS ST,BRADFORD,41.940589,-78.650717,ZIPPO MANUFACTURING CO
27874,ZOETIS LLC,601 W CORNH US KER HWY,LINCOLN,40.835490,-96.730290,ZOETIS INC
27878,ZOETIS LLC,2000 ROCKFORD RD,CHARLES CITY,43.075680,-92.752040,ZOETIS INC
19674,ZURN INDUSTRIES LLC DBA STAINLESSDRAINS.COM,4894 INTERSTATE 30 W,CADDO MILLS,33.005688,-96.230423,ZURN HOLDINGS INC.
16753,ZURN INDUSTRIES LLC DBA STAINLESSDRAINS.COM,4894 INTERSTATE 30 W,CADDO MILLS,33.005688,-96.230423,ZURN HOLDINGS INC.

In [ ]:
df3 = df2[df2['NAME'].str.startswith('EXXON')]
df3

,NAME,STREET,CITY,LAT,LONG,PARENT
30,EXXONMOBIL BATON ROUGE CHEMICAL PLANT NORTH,1836 SHADA AVE,BATON ROUGE,30.502665,-91.173395,EAST WEST COPOLYMER & RUBBER LLC
39,EXXON MOBIL CORP SPOKANE TERMINAL,6311 E SHARP AVE,SPOKANE,47.670062,-117.320917,EXXON MOBIL CORP
110,EXXONMOBIL ANCHORAGE TANK FARM,1420 LAFITON LN,PORT ALLEN,30.475226,-91.222063,EXXON MOBIL CORP
111,EXXONMOBIL ANCHORAGE TANK FARM,1420 LAFITON LN,PORT ALLEN,30.475226,-91.222063,EXXON MOBIL CORP
175,EXXON MOBIL CORP NORTH HOUSTON TERMINAL,8700 N FWY,HOUSTON,29.934890,-95.366190,EXXON MOBIL CORP
...,...,...,...,...,...,...
38251,EXXONMOBIL OIL CORP VERNON TERMINAL,2709 E 37TH ST,VERNON,34.008940,-118.221880,EXXON MOBIL CORP
38252,EXXONMOBIL OIL CORP VERNON TERMINAL,2709 E 37TH ST,VERNON,34.008940,-118.221880,EXXON MOBIL CORP
39292,EXXONMOBIL BATON ROUGE REFINERY (PART),4045 SCENIC HWY,BATON ROUGE,30.484917,-91.173920,EXXON MOBIL CORP
39426,EXXONMOBIL REFINING & SUPPLY BAYTOWN REFINERY ...,2800 DECKER DR,BAYTOWN,29.739444,-95.006944,EXXON MOBIL CORP
39427,EXXONMOBIL REFINING & SUPPLY BAYTOWN REFINERY ...,2800 DECKER DR,BAYTOWN,29.739444,-95.006944,EXXON MOBIL CORP

In [ ]:
#df5=df4[:,'NAME':'PARENT']
#df
#df3=df3.loc[:,1:5]

In [ ]:
df3=df3.drop_duplicates()ew

In [ ]:
 df3

,NAME,STREET,CITY,LAT,LONG,PARENT
30,EXXONMOBIL BATON ROUGE CHEMICAL PLANT NORTH,1836 SHADA AVE,BATON ROUGE,30.502665,-91.173395,EAST WEST COPOLYMER & RUBBER LLC
39,EXXON MOBIL CORP SPOKANE TERMINAL,6311 E SHARP AVE,SPOKANE,47.670062,-117.320917,EXXON MOBIL CORP
110,EXXONMOBIL ANCHORAGE TANK FARM,1420 LAFITON LN,PORT ALLEN,30.475226,-91.222063,EXXON MOBIL CORP
175,EXXON MOBIL CORP NORTH HOUSTON TERMINAL,8700 N FWY,HOUSTON,29.934890,-95.366190,EXXON MOBIL CORP
256,EXXON MOBIL CORP NASHVILLE TERMINAL,1741 ED TEMPLE BLVD,NASHVILLE,36.180906,-86.827665,EXXON MOBIL CORP
317,EXXONMOBIL REFINING & SUPPLY BAYTOWN REFINERY ...,2800 DECKER DR,BAYTOWN,29.739444,-95.006944,EXXON MOBIL CORP
329,EXXONMOBIL OIL CORP VERNON TERMINAL,2709 E 37TH ST,VERNON,34.008940,-118.221880,EXXON MOBIL CORP
401,EXXONMOBIL OIL CORP EAST PROVIDENCE TERMINAL,1001 WAMPANOAG TRAIL,EAST PROVIDENCE,41.787793,-71.343584,EXXON MOBIL OIL CORP
405,EXXON MOBIL CORP EVERETT TERMINAL,52 BEACHAM ST,EVERETT,42.396384,-71.060496,EXXON MOBIL CORP
470,EXXONMOBIL OIL CORP HAMMOND TERMINAL,1527 141ST ST,HAMMOND,41.639469,-87.492193,EXXONMOBIL OIL CORP
853,EXXON MOBIL CORP SAN ANTONIO TERMINAL,3214 N PAN AM EXPRESSWAY,SAN ANTONIO,29.442136,-98.436898,EXXON MOBIL CORP
861,EXXONMOBIL BATON ROUGE REFINERY (PART),4045 SCENIC HWY,BATON ROUGE,30.484917,-91.173920,EXXON MOBIL CORP
1940,EXXONMOBIL OIL CORP DES PLAINES TERMINAL,2312 TERMINAL DR,ARLINGTON HEIGHTS,42.024510,-87.948921,EXXONMOBIL OIL CORP
2302,EXXONMOBIL OIL CORP LOCKPORT TERMINAL,12909 HIGH RD,LOCKPORT,41.650306,-88.045530,EXXONMOBIL OIL CORP
34005,EXXON MOBIL CORP IRVING TERMINAL,1201 E AIRPORT FWY,IRVING,32.837410,-96.935350,EXXON MOBIL CORP

In [ ]:
df3.reset_index()

,index,NAME,STREET,CITY,LAT,LONG,PARENT
0,30,EXXONMOBIL BATON ROUGE CHEMICAL PLANT NORTH,1836 SHADA AVE,BATON ROUGE,30.502665,-91.173395,EAST WEST COPOLYMER & RUBBER LLC
1,39,EXXON MOBIL CORP SPOKANE TERMINAL,6311 E SHARP AVE,SPOKANE,47.670062,-117.320917,EXXON MOBIL CORP
2,110,EXXONMOBIL ANCHORAGE TANK FARM,1420 LAFITON LN,PORT ALLEN,30.475226,-91.222063,EXXON MOBIL CORP
3,175,EXXON MOBIL CORP NORTH HOUSTON TERMINAL,8700 N FWY,HOUSTON,29.934890,-95.366190,EXXON MOBIL CORP
4,256,EXXON MOBIL CORP NASHVILLE TERMINAL,1741 ED TEMPLE BLVD,NASHVILLE,36.180906,-86.827665,EXXON MOBIL CORP
5,317,EXXONMOBIL REFINING & SUPPLY BAYTOWN REFINERY ...,2800 DECKER DR,BAYTOWN,29.739444,-95.006944,EXXON MOBIL CORP
6,329,EXXONMOBIL OIL CORP VERNON TERMINAL,2709 E 37TH ST,VERNON,34.008940,-118.221880,EXXON MOBIL CORP
7,401,EXXONMOBIL OIL CORP EAST PROVIDENCE TERMINAL,1001 WAMPANOAG TRAIL,EAST PROVIDENCE,41.787793,-71.343584,EXXON MOBIL OIL CORP
8,405,EXXON MOBIL CORP EVERETT TERMINAL,52 BEACHAM ST,EVERETT,42.396384,-71.060496,EXXON MOBIL CORP
9,470,EXXONMOBIL OIL CORP HAMMOND TERMINAL,1527 141ST ST,HAMMOND,41.639469,-87.492193,EXXONMOBIL OIL CORP
10,853,EXXON MOBIL CORP SAN ANTONIO TERMINAL,3214 N PAN AM EXPRESSWAY,SAN ANTONIO,29.442136,-98.436898,EXXON MOBIL CORP
11,861,EXXONMOBIL BATON ROUGE REFINERY (PART),4045 SCENIC HWY,BATON ROUGE,30.484917,-91.173920,EXXON MOBIL CORP
12,1940,EXXONMOBIL OIL CORP DES PLAINES TERMINAL,2312 TERMINAL DR,ARLINGTON HEIGHTS,42.024510,-87.948921,EXXONMOBIL OIL CORP
13,2302,EXXONMOBIL OIL CORP LOCKPORT TERMINAL,12909 HIGH RD,LOCKPORT,41.650306,-88.045530,EXXONMOBIL OIL CORP
14,34005,EXXON MOBIL CORP IRVING TERMINAL,1201 E AIRPORT FWY,IRVING,32.837410,-96.935350,EXXON MOBIL CORP